name: Deployment
on: push
jobs:
    quality-check:
        runs-on: ubuntu-latest
        steps:
            - name: Clone code
              uses: actions/checkout@v3
            - name: Install NodeJs
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install dependencies
              run: npm ci
            - name: Linting
              run: npm run lint
            - name: Testing
              run: npm test
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Clone code
              uses: actions/checkout@v3
            - name: Install NodeJs
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install dependencies
              run: npm ci
            - name: Build
              run: npm run build
            - name: Deploy
              run: echo "Deploying..."